# Generated by Django 5.2.7 on 2025-11-06 23:57

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('Senior', 'Idosos'), ('Animal', 'Animais'), ('Child', 'Crianças'), ('Environmental', 'Ambiental')], max_length=20, verbose_name='Categoria')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('done', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=16, verbose_name='Sitação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('Senior', 'Idosos'), ('Animal', 'Animais'), ('Child', 'Crianças'), ('Environmental', 'Ambiental')], max_length=20, verbose_name='Categoria')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('done', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=16, verbose_name='Situação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do doador')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do doador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de Crédito'), ('cash', 'Dinheiro'), ('bank_transfer', 'Transferência Bancária'), ('other', 'Outro')], max_length=20, verbose_name='Método')),
                ('timestamp', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('source_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fundraising.action', verbose_name='Ação relacionada')),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fundraising.campaign', verbose_name='Campanha relacionada')),
            ],
            options={
                'verbose_name': 'doação',
                'verbose_name_plural': 'doações',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('paid_at', models.DateTimeField(verbose_name='Data de Pagamento')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/', validators=[core.validators.validate_attachment], verbose_name='Comprovante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fundraising.action', verbose_name='Ação relacionada')),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fundraising.campaign', verbose_name='Campanha relacionada')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
            },
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['status', 'category'], name='fundraising_status_125293_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'category'], name='fundraising_status_549e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['timestamp', 'method'], name='fundraising_timesta_2d841f_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_action__isnull', False), ('source_campaign__isnull', True)), models.Q(('source_action__isnull', True), ('source_campaign__isnull', False)), _connector='OR'), name='donation_one_source'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_at'], name='fundraising_paid_at_249a8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('related_action__isnull', False), ('related_campaign__isnull', True)), models.Q(('related_action__isnull', True), ('related_campaign__isnull', False)), _connector='OR'), name='expense_one_relation'),
        ),
    ]
