# Generated by Django 5.2.7 on 2025-11-24 15:25

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da entidade')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Pessoa de contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('criancas', 'Crianças'), ('idosos', 'Idosos'), ('animais', 'Animais'), ('meio_ambiente', 'Meio Ambiente'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria do beneficiário')),
            ],
            options={
                'verbose_name': 'beneficiário',
                'verbose_name_plural': 'beneficiários',
                'indexes': [models.Index(fields=['category', 'name'], name='fundraising_categor_737b54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('Senior', 'Idosos'), ('Animal', 'Animais'), ('Child', 'Crianças'), ('Environmental', 'Ambiental')], max_length=20, verbose_name='Categoria')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('done', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=16, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
                'indexes': [models.Index(fields=['status', 'category'], name='fundraising_status_549e5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('Senior', 'Idosos'), ('Animal', 'Animais'), ('Child', 'Crianças'), ('Environmental', 'Ambiental')], max_length=20, verbose_name='Categoria')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('done', 'Concluído'), ('archived', 'Arquivado')], default='draft', max_length=16, verbose_name='Sitação')),
                ('people_impacted', models.PositiveIntegerField(default=0)),
                ('participants', models.ManyToManyField(blank=True, related_name='actions_participated', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='fundraising.beneficiary', verbose_name='Entidade beneficiada')),
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'indexes': [models.Index(fields=['status', 'category'], name='fundraising_status_125293_idx')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do doador')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do doador')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de Crédito'), ('cash', 'Dinheiro'), ('bank_transfer', 'Transferência Bancária'), ('other', 'Outro')], max_length=20, verbose_name='Método')),
                ('timestamp', models.DateTimeField()),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fundraising.campaign', verbose_name='Campanha relacionada')),
            ],
            options={
                'verbose_name': 'doação',
                'verbose_name_plural': 'doações',
                'indexes': [models.Index(fields=['timestamp', 'method'], name='fundraising_timesta_2d841f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('paid_at', models.DateTimeField(verbose_name='Data de Pagamento')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/', validators=[core.validators.validate_attachment], verbose_name='Comprovante')),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fundraising.campaign', verbose_name='Campanha relacionada')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'indexes': [models.Index(fields=['paid_at'], name='fundraising_paid_at_249a8a_idx')],
            },
        ),
    ]
