# Generated by Django 5.2.7 on 2025-11-08 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.AddField(
            model_name='action',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='actions_participated', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
