# Generated by Django 5.2.7 on 2025-11-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_remove_action_created_by_remove_campaign_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da entidade')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Pessoa de contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('criancas', 'Crianças'), ('idosos', 'Idosos'), ('animais', 'Animais'), ('meio_ambiente', 'Meio Ambiente'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria do beneficiário')),
            ],
            options={
                'verbose_name': 'beneficiário',
                'verbose_name_plural': 'beneficiários',
            },
        ),
        migrations.RemoveConstraint(
            model_name='donation',
            name='donation_one_source',
        ),
        migrations.RemoveConstraint(
            model_name='expense',
            name='expense_one_relation',
        ),
        migrations.RemoveField(
            model_name='action',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='source_action',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='related_action',
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['category', 'name'], name='fundraising_categor_737b54_idx'),
        ),
        migrations.AddField(
            model_name='action',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='fundraising.beneficiary', verbose_name='Entidade beneficiada'),
        ),
    ]
